support sendHttpFile
swow/swow pull request #168
Opened 2023-03-01 07:16 UTC by PandaLIU-1111

2023-03-01 07:24 UTC, twose requested changes

2023-03-01 07:24 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +            $file = new SplFileInfo($filename);
SplFileInfo->getExtension() 其实就是拿文件名来获取扩展名，直接对 filename 用 pathinfo 即可

2023-03-01 07:24 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +            $response = $response->withHeader('Content-Type', MimeType::fromExtension($file->getExtension()));
上下有点混乱，上面用的 `withHeader`，下面对headers直接进行了操作，不如直接都对 `$headers` 操作，少一次 clone。

2023-03-01 07:24 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        $headers['Content-Length'] = filesize($filename);
需要考虑，可能 `Content-Length` 标头已经存在的情况，并且可能它不是 `Content-Length`，而是 `content-length`。

2023-03-01 07:24 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        $headers['Content-Length'] = filesize($filename);
还有用户设置的 Content-Length 和 实际发送文件长度不一致的情况，建议是判断一下不允许用户设置 Content-Length，有的话就抛错，这样处理简单。

2023-03-02 05:57 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        if ($response->hasHeader('Content-Length') || $response->hasHeader('content-length')) {
hasHeader 是 不区分大小写的

2023-03-02 08:34 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        $headers['Content-Length'] = filesize($filename);
```suggestion
        $headers['Content-Length'] = $length > 0 ? filesize($filename) : $length;
```

2023-03-02 08:34 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        if (! $response->hasHeader('Content-Type')) {
```suggestion
        if (!$response->hasHeader('Content-Type')) {
```

2023-03-02 08:35 UTC, twose commented on lib/swow-stub/src/Swow.php
> +        public function sendFile(string $filename, int $offset = 0, int $length = -1, ?int $timeout = null): int { }
```suggestion
        public function sendFile(string $filename, int $offset = 0, int $length = 0, ?int $timeout = null): int { }
```

2023-03-02 08:36 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        if ($response->hasHeader('Content-Length')) {
最好是把检查的代码放在最上面。

2023-03-03 19:16 UTC, twose requested changes

2023-03-03 19:16 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        $headers['Content-Length'] = $length > 0 ? filesize($filename) : $length;
写反了

2023-03-06 03:20 UTC, twose requested changes

2023-03-06 03:20 UTC, twose commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        $headers['Content-Length'] = $length < 0 ? filesize($filename) : $length;
大于号反过来是小于等于不是小于

2023-03-06 03:22 UTC, PandaLIU-1111 commented on lib/swow-library/src/Psr7/Server/ServerConnection.php
> +        $headers['Content-Length'] = $length < 0 ? filesize($filename) : $length;
哈哈哈，尴尬，我改的时候也是觉得有点诡异

2023-03-06 03:23 UTC, twose requested changes
code style 检查没过，跑一下 composer cs-fix

2023-03-06 03:42 UTC, PandaLIU-1111 commented
跑完了

2023-03-07 02:51 UTC, twose approved these changes

2023-03-07 02:53 UTC, merged