fix setParsedBody params type
swow/swow pull request #174
Opened 2023-03-19 15:34 UTC by duxphp

The PSR-7 standard protocol allows the types that can be written with withParsedBody to be null, array, or object. However, using the Psr library from the standard library will result in a type error. Please refer to this address for more information.
 https://github.com/php-fig/http-message/blob/efd67d1dc14a7ef4fc4e518e7dee91c271d524e4/src/ServerRequestInterface.php#L197

2023-03-20 06:31 UTC, twose requested changes

2023-03-20 06:31 UTC, twose commented on lib/swow-library/src/Psr7/Message/ServerRequest.php
>      /** @param array<mixed>|object $data */
```suggestion
    /** @param null|array<mixed>|object $data */
```

2023-03-20 06:31 UTC, twose commented on lib/swow-library/src/Psr7/Message/ServerRequest.php
line 36 ~ 37 should also be:

```php
    /** @var null|array<mixed>|object */
    protected null|array|object $parsedBody;
```

2023-03-20 10:07 UTC, duxphp reviewed
Add comment with null parameter

2023-03-20 10:20 UTC, twose commented on lib/swow-library/src/Psr7/Message/ServerRequest.php
Do not forget it, this is property declaration.

2023-03-21 14:27 UTC, duxphp reviewed
add params

2023-03-24 08:32 UTC, twose commented
算了，我翻译一下，这个文件第 36 ~ 37 行，属性定义的地方也要改... 你只改方法上的声明没改属性的声明会出错的...

2023-03-24 08:32 UTC, twose commented
算了，我翻译一下，这个文件第 36 ~ 37 行，属性定义的地方也要改... 你只改方法上的声明没改属性的声明会出错的...

2023-03-24 12:04 UTC, duxphp reviewed
fix parameter declaration

2023-03-24 12:05 UTC, duxphp commented
> 算了，我翻译一下，这个文件第 36 ~ 37 行，属性定义的地方也要改... 你只改方法上的声明没改属性的声明会出错的...

忘了需要再次编辑才能提交，pr操作不熟悉

2023-05-12 09:14 UTC, twose submitted a review, later dismissed

2023-05-19 08:52 UTC, twose approved these changes

2023-05-25 08:01 UTC, twose submitted a review, later dismissed

2023-05-25 08:18 UTC, twose approved these changes

2023-05-25 08:57 UTC, merged