Added Http Client
swow/swow pull request #18
Opened 2020-10-21 08:50 UTC by limingxinleo

2020-10-22 09:39 UTC, twose requested changes

2020-10-22 09:39 UTC, twose commented on composer.json
> +        "psr/http-client": "^1.0",
这个排在message后面是不是好一点?

2020-10-22 09:39 UTC, twose commented on lib/Swow/Http/Client.php
> +    protected $maxHeaderLength = 8192;
为什么要硬编码, 这些配置也是可以复用代码的

2020-10-22 09:39 UTC, twose commented on lib/Swow/Http/Client.php
> +        if (!$this->isEstablished()) {
这里改成 checkLiveness就能实现断线重连

2020-10-22 09:39 UTC, twose commented on lib/Swow/Http/Client.php
> +                case Errno\ETIMEDOUT:
SocketException全都属于网络错误吧?

2020-10-22 09:39 UTC, twose commented on lib/Swow/Http/Client.php
> +            Buffer::create(),
这里不对, 一个buffer就算解析完了, 尾部也可能残留着下一个包的数据

2020-10-22 12:25 UTC, limingxinleo commented on composer.json
> +        "psr/http-client": "^1.0",
这个排序是按照 "sort-packages": true 来排的

就是按照字母顺序

2020-10-23 06:08 UTC, twose approved these changes

2020-10-23 06:09 UTC, merged