Support two dimensional array for headers
swow/swow pull request #20
Opened 2020-10-21 10:30 UTC by limingxinleo

qps 在 75000 - 80000 波动

大概率都在 78000 以上

2020-10-21 10:41 UTC, limingxinleo commented
这个可以后面再看，headerNames 处理后，会删掉一些代码

2020-10-22 09:29 UTC, twose requested changes

2020-10-22 09:29 UTC, twose commented on lib/Swow/Http/Message.php
> +            return $this;
一般函数只有一个出口是最好的

2020-10-22 09:29 UTC, twose commented on lib/Swow/Http/Message.php
> +        $this->headers[$name] = $value;
这种可以写成一行三元表达式吧

2020-10-22 09:29 UTC, twose commented on lib/Swow/Http/Message.php
> +        if (is_null($name)) {
保持风格一致, 用 === null 比较好

2020-10-22 12:09 UTC, twose approved these changes

2020-10-22 12:21 UTC, merged