Use !== '' to replace the str_len function
swow/swow pull request #87
Opened 2021-09-03 07:13 UTC by codingheping

Use !== '' to replace the str_len function and add some function return types

2021-09-03 07:14 UTC, codingheping commented
@twose

2021-09-03 08:54 UTC, twose requested changes

2021-09-03 08:54 UTC, twose commented on lib/src/Swow/Util/IDE/ExtensionGenerator.php
> +                        $defaultParamValueTip = ($defaultParamValueString);
这里应该是强转为字符串

2021-09-03 08:54 UTC, twose commented on lib/src/Swow/Util/IDE/ExtensionGenerator.php
> +            $paramType = (ltrim((string) $param->getType(), '?') ?: 'mixed');
括号可以去掉了

2021-09-03 08:54 UTC, twose commented on lib/src/Swow/Debug/Debugger.php
> +                            usleep(($time * 1000 * 1000));
用户传入浮点数时会报错

2021-09-03 08:54 UTC, twose commented on lib/src/Swow/Debug/Debugger.php
> +    protected static function getSourceFileContentAsTable(string $filename, int $line, SplFileObject &$sourceFile = null, int $lineCount = self::SOURCE_FILE_DEFAULT_LINE_COUNT): array
这是为什么?

2021-09-03 08:54 UTC, twose commented on lib/src/Swow/Util/IDE/ExtensionGenerator.php
> +                if (is_string($defaultParamValue) && ($paramType !== 'string' || preg_match('/[^\W]/', $defaultParamValue) > 0)) {
没有去掉`^`

2021-09-06 02:06 UTC, codingheping commented on lib/src/Swow/Debug/Debugger.php
> +                            usleep(($time * 1000 * 1000));
按照使用习惯，这里应该不能传入浮点数。

2021-09-06 02:10 UTC, codingheping commented on lib/src/Swow/Debug/Debugger.php
> +    protected static function getSourceFileContentAsTable(string $filename, int $line, SplFileObject &$sourceFile = null, int $lineCount = self::SOURCE_FILE_DEFAULT_LINE_COUNT): array
$filename主要和 SplFileObject 构造函数里的参数名一致

2021-09-06 06:57 UTC, twose approved these changes

2021-09-06 06:59 UTC, merged